Доработка manifest
htmlacademy-htmlcss/1819647-nerds-31 pull request #5
Opened 2021-05-31 16:31 UTC by Herodont

Изменил формат с ico на svg
Опечатку исправил

Но  я так и не понял, почему ты указал на:
type="image/svg+xml"

2021-06-05 11:32 UTC, baileys-li commented
> type="image/svg+xml"

У тебя ж был ` type="image/svg+xml"`, но формат ico

2021-06-05 11:42 UTC, baileys-li reviewed
> Все цвета вынесены в кастомные свойства в селектор :root.

Раз в задании, то лучше сделать. Это и в учебнике [есть](https://up.htmlacademy.ru/htmlcss/31/module/4/item/10), и на лекции [показывали](https://youtu.be/yaOW81SIeyQ?t=2578)

2021-06-05 11:42 UTC, baileys-li commented on catalog.html
> +	<link rel="stylesheet" href="normalize.css">
Библиотеки вроде `normalize` лучше подключать до основных стилей.  Поскольку стили применяются сверху вниз и лучше всегда знать, что библиотечные стили на перезапишут кастомные

2021-06-05 12:05 UTC, baileys-li requested changes

2021-06-05 12:05 UTC, baileys-li commented on index.html
> +		<h1 class="title-to-hide">Веб-студия «Нёрдс»</h1>
Спешишь.
1. `title-to-hide` плохое название для класса, потому скрывать часто нужно не только заголовки, но и другие штуки.
2. `display: none;` плохое скрытие, потому что нам нужно оставить текст дсотупным для скринридеров. Скорее всего вас обучат этому в модуле про декоративные элементы, но если хочешь себе спойлернуть, то [вот](https://htmlacademy.ru/blog/boost/frontend/short-12)
3. Ты можешь временно вместо `class="title-to-hide"` сделать `<h1 hidden>`, если тебе не удобно, что они не скрыты, но писать `visually-hidden` пока не хочешь

2021-06-05 12:05 UTC, baileys-li commented on index.html
> +						<button class="slider-button" type="button" href="#">Узнать больше</button>
Хз, зачем ты тут заменил ссылку на кнопку, но тогда `href="#"` убери

2021-06-05 12:05 UTC, baileys-li commented on index.html
>  					<img src="img/clients/logo_htmlacademy 1.png" alt="HTML и CSS. Профессиональная вёрстка сайтов" width="199" height="57">
Всё-таки лучше бы было сохранить лого академии в СВГ

2021-06-05 12:05 UTC, baileys-li commented on index.html
> +				<a class="cases-item" href="https://htmlacademy.ru/intensive/htmlcss">
`text-decoration: none` на этот класс

2021-06-05 12:25 UTC, Herodont commented on style.css
> +	text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
Да, случайно добавил в своей копии тень в фигме

2021-06-05 12:50 UTC, Herodont commented on index.html
> +			<a class="socials-item" href="#"><img src="img/Footer/vk.svg" alt="Вконтакте" width="26" height="15"></a>
если в макете фон белый, то мне нужно указывать это и в CSS? Или ты имеешь ввиду серый фон для class="socials-item"?

2021-06-05 16:35 UTC, Herodont commented on index.html
> +				<a class="cases-item" href="https://htmlacademy.ru/intensive/htmlcss">
На изображении же нет оформления, для чего нужно их убрать?

2021-06-05 17:04 UTC, baileys-li commented
> Описание состояний интерактивных элементов, которые описаны в стайлгайде. На этом этапе задавайте только текстовые параметры и параметры фона.
Их вообще нет

2021-06-06 16:17 UTC, baileys-li commented
То что кидал в ЛС осталось

`font-style: normal;`
![image](https://user-images.githubusercontent.com/47776594/120931654-3e585780-c6fb-11eb-8d1e-60bb21125ad4.png)

Не работает из-за повтора айдишника. Ещё раз: айдишники **в разметке должны быть уникальными**   
![image](https://user-images.githubusercontent.com/47776594/120931755-a7d86600-c6fb-11eb-96e5-ecff27df50e1.png)

2021-06-06 16:22 UTC, baileys-li commented
Вес шрифта неправильный отрисовался, а всё потому что ты через гугл подключил только вес 500
![image](https://user-images.githubusercontent.com/47776594/120931885-28976200-c6fc-11eb-9f33-79334ea965ef.png)

А ещё подключил кучу всякой фигни, типо греческих символов, вьетнамских, расширенных греческих и кирилических. Камон, тут обычный русский текст с изредка английскими словами.

Ты так увеличиваешь загрузку страниц

2021-06-06 16:22 UTC, baileys-li requested changes

2021-06-06 16:22 UTC, baileys-li commented on style.css
> +}
Нет, так делать нельзя. Сделай общий класс `button`, не id
У тебя не должен повторяться один и тот же id в разметке. Это грубая ошибка

2021-06-07 16:59 UTC, merged